version: '3.8'

services:
  app:
    build: .
    volumes:
      - $PWD/:/usr/src/app:cached
    ports:
      - "${APP_PORT:-8000}:8000"
    command: tail -f /dev/null
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=sample
      - TZ=Asia/Tokyo
volumes:
  db-data:
